# Generated by Django 4.2.23 on 2025-07-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electronicproduct',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='foodproduct',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='serviceproduct',
            name='subcategory',
        ),
        migrations.AlterField(
            model_name='electronicproduct',
            name='sku',
            field=models.CharField(default='VAMS-SKU-8F189B96', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='sku',
            field=models.CharField(default='VAMS-SKU-8F189B96', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceproduct',
            name='sku',
            field=models.CharField(default='VAMS-SKU-8F189B96', max_length=100, unique=True),
        ),
    ]
