# Generated by Django 4.2.23 on 2025-08-02 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='VAMS-SKU-5E06B871', max_length=100, unique=True),
        ),
    ]
