# Generated by Django 4.2.23 on 2025-08-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='VAMS-SKU-E99A2695', max_length=100, unique=True),
        ),
    ]
