# Generated by Django 4.2.23 on 2025-07-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_electronicproduct_subcategory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicproduct',
            name='sku',
            field=models.CharField(default='VAMS-SKU-5CB3E437', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='sku',
            field=models.CharField(default='VAMS-SKU-5CB3E437', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceproduct',
            name='sku',
            field=models.CharField(default='VAMS-SKU-5CB3E437', max_length=100, unique=True),
        ),
    ]
