# Generated by Django 4.2.23 on 2025-08-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(default='VAMS-SKU-20652392', max_length=100, unique=True),
        ),
    ]
