# Generated by Django 4.2.23 on 2025-07-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_electronicproduct_sku_alter_foodproduct_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electronicproduct',
            name='sku',
            field=models.CharField(default='VAMS-SKU-3970BC8B', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='foodproduct',
            name='sku',
            field=models.CharField(default='VAMS-SKU-3970BC8B', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceproduct',
            name='sku',
            field=models.CharField(default='VAMS-SKU-3970BC8B', max_length=100, unique=True),
        ),
    ]
