# Generated by Django 4.2.23 on 2025-07-30 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='Slug')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='category.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='CategorySubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
            ],
            options={
                'verbose_name': 'CategorySubscriptionPlan',
                'verbose_name_plural': 'CategorySubscriptionPlans',
            },
        ),
        migrations.CreateModel(
            name='CategoryRefundRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_allowed', models.BooleanField(default=False)),
                ('return_window_days', models.PositiveIntegerField(default=0)),
                ('refund_type', models.CharField(choices=[('wallet', 'Wallet'), ('original', 'Original Payment Method'), ('none', 'No Refund')], default='none', max_length=10)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_rules', to='category.category')),
            ],
            options={
                'verbose_name': 'CategoryRefundRule',
                'verbose_name_plural': 'CategoryRefundRules',
            },
        ),
    ]
