# Generated by Django 4.2.23 on 2025-07-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otprecord_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otprecord',
            name='otp_code',
            field=models.CharField(max_length=10),
        ),
    ]
