# Generated by Django 4.2.23 on 2025-07-21 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_parent_category_delete_subcategory'),
        ('accounts', '0004_alter_otprecord_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category'),
        ),
    ]
