# Generated by Django 4.2.23 on 2025-07-27 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_vendorprofile_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bdaprofile',
            old_name='assigned_area',
            new_name='region',
        ),
    ]
